# calculating rpkm based on formula provided [here](https://www.rna-seqblog.com/rpkm-fpkm-and-tpm-clearly-explained/)

In [1]:
import numpy as np
import pandas as pd
import scipy.stats as stats

In [2]:
df = pd.read_csv('E:\\DATA\\microglia_sequencing\\GSE99622_hanamsagar2017_raw_reads.csv')
df2 = pd.read_excel('E:\\DATA\\microglia_sequencing\\Blbo_Mgla_RPKM_calculation_example.xlsx')

In [3]:
## subsetting the secondary dataframe to just grab the columns containing transcript length info for the merge

df2 = df2[['Transcript', 'Transcript length']]

In [4]:
df

,Gene,Transcript,Best,F_E18 1,M_E18 1,F_E18 3,M_E18 4,F_P14 1,F_P14 2,F_P14 3,...,F_P60_LPS 3,M_P60_LPS 3,M_P60_LPS 4,M_P60_LPS 5,M_P60_LPS 6,M_P60_Sal 1,M_P60_Sal 2,M_P60_Sal 3,M_P60_Sal 4,F_P60_Sal 6
0,Zfp85-rs1,NM_001001130,1,7,18,9,0,4,5,1,...,6,4,1,1,11,6,19,10,17,6
1,Scap,NM_001001144,1,133,181,132,53,98,152,141,...,64,26,35,39,59,121,207,128,110,8
2,Zfp458,NM_001001152,1,20,13,14,0,5,9,4,...,14,9,6,5,9,18,22,7,10,5
3,Fbxo41,NM_001001160,1,41,15,29,7,1,3,7,...,0,0,1,1,0,2,4,0,1,0
4,Taf9b,NM_001001176,1,38,32,37,15,30,43,64,...,8,18,30,18,31,65,41,52,55,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28639,4933401P06Rik,NR_045505,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
28640,4933405E24Rik,NR_045506,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28641,4933412O06Rik,NR_045507,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
28642,4933413L06Rik,NR_045508,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28643,1700022A22Rik,NR_045509,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
df2

         Transcript  Transcript length
0      NM_001166372               4223
1      NM_001166375               3942
2         NM_175188               4391
3         NM_145486               3452
4         NM_177115               1754
...             ...                ...
28639  NM_001033634              10654
28640     NM_011777               2438
28641  NM_001045536              11150
28642  NM_001080755               7600
28643     NM_198416               7539

[28644 rows x 2 columns]

In [6]:
### merging the two dataframes by transcript column

df_merged = pd.merge(df, df2, on = 'Transcript')

In [7]:
df_merged.groupby(['Gene']).mean()

,Best,F_E18 1,M_E18 1,F_E18 3,M_E18 4,F_P14 1,F_P14 2,F_P14 3,F_P14 4,F_P14 5,...,M_P60_LPS 3,M_P60_LPS 4,M_P60_LPS 5,M_P60_LPS 6,M_P60_Sal 1,M_P60_Sal 2,M_P60_Sal 3,M_P60_Sal 4,F_P60_Sal 6,Transcript length
Gene,,,,,,,,,,,,,,,,,,,,,
0610005C13Rik,0.5,3.0,0.0,1.0,0.0,1.0,0.0,2.5,4.0,0.5,...,0.0,0.5,1.0,1.0,2.0,3.0,0.0,3.0,0.0,1018.5
0610007C21Rik,1.0,145.0,186.0,150.0,488.0,160.0,202.0,181.0,263.0,204.0,...,48.0,55.0,57.0,109.0,179.0,291.0,175.0,213.0,198.0,961.0
0610007L01Rik,0.5,198.0,90.5,159.0,64.0,156.5,231.0,188.0,256.0,173.0,...,45.0,66.0,76.0,84.0,215.0,230.0,160.0,197.0,44.0,3638.0
0610007P08Rik,0.5,66.0,35.0,73.5,8.5,29.0,69.5,61.5,63.5,46.5,...,22.0,16.5,16.0,23.0,82.0,78.5,54.0,75.5,9.0,4139.5
0610007P14Rik,1.0,74.0,110.0,84.0,162.0,21.0,27.0,42.0,38.0,42.0,...,8.0,12.0,13.0,7.0,33.0,49.0,42.0,39.0,31.0,1185.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zyx,1.0,293.0,231.0,253.0,43.0,539.0,397.0,365.0,938.0,324.0,...,91.0,174.0,239.0,141.0,140.0,489.0,109.0,201.0,13.0,2438.0
Zzef1,1.0,215.0,89.0,179.0,14.0,179.0,251.0,179.0,291.0,178.0,...,95.0,84.0,104.0,119.0,229.0,324.0,214.0,173.0,24.0,11150.0
Zzz3,0.5,229.0,132.0,225.0,9.0,167.0,282.0,219.0,281.0,198.5,...,125.0,94.0,92.0,140.0,259.0,253.0,158.0,193.0,64.0,7569.5
a,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,692.0
l7Rn6,1.0,48.0,73.0,60.0,107.0,28.0,27.0,36.0,40.0,29.0,...,20.0,15.0,11.0,11.0,48.0,34.0,54.0,49.0,51.0,1045.0

In [8]:
### first we should drop any duplicate genes (only keep the uniques)

## i am doing that here by dropping rows that have a 'Best' value of 0
## then i get rid of the 'Best' and 'Transcript' columns, as they will not be helpful moving forward

for i in range(len(df)):
    if df_merged['Best'][i] == 0:
        df_merged.drop(i, axis = 0, inplace = True)
        
df_merged.drop(columns = {'Best', 'Transcript'}, inplace = True)

In [9]:
df_merged

,Gene,F_E18 1,M_E18 1,F_E18 3,M_E18 4,F_P14 1,F_P14 2,F_P14 3,F_P14 4,F_P14 5,...,M_P60_LPS 3,M_P60_LPS 4,M_P60_LPS 5,M_P60_LPS 6,M_P60_Sal 1,M_P60_Sal 2,M_P60_Sal 3,M_P60_Sal 4,F_P60_Sal 6,Transcript length
0,Zfp85-rs1,7,18,9,0,4,5,1,5,4,...,4,1,1,11,6,19,10,17,6,2218
1,Scap,133,181,132,53,98,152,141,175,110,...,26,35,39,59,121,207,128,110,8,4286
2,Zfp458,20,13,14,0,5,9,4,5,5,...,9,6,5,9,18,22,7,10,5,3488
3,Fbxo41,41,15,29,7,1,3,7,3,4,...,0,1,1,0,2,4,0,1,0,6562
4,Taf9b,38,32,37,15,30,43,64,52,64,...,18,30,18,31,65,41,52,55,30,2583
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28639,4933401P06Rik,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1491
28640,4933405E24Rik,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1081
28641,4933412O06Rik,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1123
28642,4933413L06Rik,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,922
28643,1700022A22Rik,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,855

In [10]:
## obtaining sample indices from columns in the dataframe

samples = df_merged.columns[1:-1]

In [11]:
### create the scaling factor by dividing the total reads for each sample by 1,000,000

scaling_factor = np.zeros(shape = len(samples))
i = -1

for sample in samples:
    i = i + 1
    scaling_factor[i] = np.sum(df_merged[sample])/1000000

In [12]:
scaling_factor

array([2.280249, 1.642408, 1.911439, 1.350713, 1.732352, 2.48565 ,
       2.229777, 2.932799, 1.921692, 0.860919, 0.891773, 3.441194,
       2.975816, 2.285897, 1.849794, 2.378107, 2.737281, 1.960248,
       1.131966, 0.791256, 0.832437, 0.952973, 1.235167, 1.377098,
       1.309759, 3.118656, 0.958471, 2.539386, 0.850724, 0.865073,
       2.336264, 1.061145, 2.289659, 2.626224, 2.707992, 2.411309,
       2.064459, 2.105607, 1.024998, 0.957797, 0.959757, 0.923115,
       1.156933, 1.08747 , 2.404167, 2.516717, 2.283997, 1.889693,
       3.014192, 0.886629, 0.955904, 0.840522, 0.942251, 0.895419,
       1.310151, 2.343862, 3.176221, 1.947044, 2.165314, 0.791292])

In [13]:
### creating rpm by dividing each read count by the 'per million' scaling factor created above

rpm = df_merged.copy()
i = -1

for sample in samples:
    i = i + 1
    rpm[sample] = df_merged[sample]/scaling_factor[i]

In [14]:
rpm

,Gene,F_E18 1,M_E18 1,F_E18 3,M_E18 4,F_P14 1,F_P14 2,F_P14 3,F_P14 4,F_P14 5,...,M_P60_LPS 3,M_P60_LPS 4,M_P60_LPS 5,M_P60_LPS 6,M_P60_Sal 1,M_P60_Sal 2,M_P60_Sal 3,M_P60_Sal 4,F_P60_Sal 6,Transcript length
0,Zfp85-rs1,3.069840,10.959518,4.708494,0.000000,2.309000,2.011546,0.448475,1.704856,2.081499,...,4.758947,1.061288,1.116796,8.395979,2.559878,5.981952,5.135991,7.851055,7.582536,2218
1,Scap,58.326963,110.204042,69.057919,39.238535,56.570489,61.151007,63.235023,59.669960,57.241223,...,30.933158,37.145092,43.555028,45.032977,51.624200,65.171787,65.740682,50.800946,10.110048,4286
2,Zfp458,8.770972,7.915207,7.324325,0.000000,2.886249,3.620783,1.793901,1.704856,2.601874,...,10.707632,6.367730,5.583978,6.869437,7.679633,6.926470,3.595194,4.618268,6.318780,3488
3,Fbxo41,17.980492,9.132932,15.171816,5.182448,0.577250,1.206928,3.139327,1.022914,2.081499,...,0.000000,1.061288,1.116796,0.000000,0.853293,1.259358,0.000000,0.461827,0.000000,6562
4,Taf9b,16.664847,19.483588,19.357144,11.105246,17.317497,17.299298,28.702422,17.730502,33.303984,...,21.415263,31.838650,20.102321,23.661395,27.732008,12.908422,26.707152,25.400473,37.912680,2583
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28639,4933401P06Rik,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.763271,0.000000,0.000000,0.000000,0.000000,0.000000,1491
28640,4933405E24Rik,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1081
28641,4933412O06Rik,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.189737,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1123
28642,4933413L06Rik,0.438549,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,922
28643,1700022A22Rik,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,855

In [15]:
### calculating RPKM by dividing the rpm values by length of transcript

rpkm = rpm[samples].div(df_merged['Transcript length']/1000, axis=0)

In [16]:
rpkm = rpkm[rpkm.all(axis = 1)]

In [17]:
age = [0] * 60
tx = [0] * 60
sex = [0] * 60

i = -1
for sample in samples:
    i = i + 1
    if 'LPS' in sample:
        tx[i] = 'LPS'
    else:
        tx[i] = 'SAL'

i = -1
for sample in samples:
    i = i + 1
    if 'M' in sample:
        sex[i] = 'Male'
    else:
        sex[i] = 'Female'
        
i = -1
for sample in samples:
    i = i + 1
    if 'E18' in sample:
        age[i] = 'E18'
    if 'P4' in sample:
        age[i] = 'P4'
    if 'P14' in sample:
        age[i] = 'P14'
    if 'P60_LPS' in sample:
        age[i] = 'P60 + LPS'
    if 'P60_SAL' in sample:
        age[i] = 'P60 + SAL'
        
for i in range(len(age)):
    if age[i] == 0:
        age[i] = 'P60'
        
age = np.array(age).astype('str')

In [18]:
rpkm.columns = [age, sex, tx, samples]

In [19]:
### reintroducing the gene column

rpkm['gene'] = df_merged['Gene']

In [20]:
rpkm.melt(id_vars = 'gene', var_name = ['age', 'sex', 'tx', 'sample'], value_name = 'expression')

                 gene  age     sex   tx       sample  expression
0                Scap  E18  Female  SAL      F_E18 1   13.608718
1               Taf9b  E18  Female  SAL      F_E18 1    6.451741
2            BC031181  E18  Female  SAL      F_E18 1   56.127519
3               Baz2b  E18  Female  SAL      F_E18 1   12.365092
4             Tmem204  E18  Female  SAL      F_E18 1   11.832677
...               ...  ...     ...  ...          ...         ...
565855  4930592A05Rik  P60  Female  SAL  F_P60_Sal 6   40.198997
565856        Gm10336  P60  Female  SAL  F_P60_Sal 6    6.365685
565857  2810013P06Rik  P60  Female  SAL  F_P60_Sal 6    1.869462
565858  4931403E22Rik  P60  Female  SAL  F_P60_Sal 6    7.567401
565859  4930549G23Rik  P60  Female  SAL  F_P60_Sal 6   21.788896

[565860 rows x 6 columns]

In [21]:
(rpkm.melt(id_vars = 'gene', var_name = ['age', 'sex', 'tx', 'sample'], value_name = 'expression').
to_csv('C:\\Users\\Ben\Dropbox\\bilbo_lab_spr2020\\microglia-seq_website\\microglia-seq\\shiny-app_200507\\GSE99622_hanamsagar2017_rpkm.csv'))

In [22]:
rpkm

             E18                                           P14             \
          Female        Male     Female        Male     Female
             SAL         SAL        SAL         SAL        SAL
         F_E18 1     M_E18 1    F_E18 3     M_E18 4    F_P14 1    F_P14 2
1      13.608718   25.712562  16.112440    9.155048  13.198901  14.267617
4       6.451741    7.543007   7.494055    4.299360   6.704412   6.697367
9      56.127519  108.746146  61.460769  269.410932  29.220864  42.267448
10     12.365092    8.698030  11.145142    1.298859  11.139910  12.402015
11     11.832677    6.160494   5.293417   23.721155  15.899519  19.448339
...          ...         ...        ...         ...        ...        ...
28347   7.846794    3.631384   6.760595   29.437365  10.902334  18.795760
28407   5.929475    5.810985   6.102679    0.196275  13.314088  12.265526
28432   9.947355   10.207747  10.060886    8.031407   3.700320   5.356188
28467  16.412747    8.203232   9.398193    8.866464  15.554638  13.249706
28534  24.195785   11.547385  13.530157   20.423441  15.924135   9.710913

                                                   ...   P60 + LPS  \
                                                   ...        Male
                                                   ...         LPS
         F_P14 3    F_P14 4    F_P14 5    F_P14 6  ... M_P60_LPS 3
1      14.753855  13.922063  13.355395  10.840406  ...    7.217256
4      11.112049   6.864306  12.893529   9.893182  ...    8.290849
9      40.692605  28.332851  58.150760  46.595107  ...   48.862163
10     10.453185  12.262999   8.803332  10.625703  ...   21.468936
11     20.923807  12.074865  19.013130  10.446763  ...    2.006302
...          ...        ...        ...        ...  ...         ...
28347  22.290027  12.201753  27.415370  21.937813  ...    8.278487
28407  11.295111   9.491510   6.483991  12.625538  ...   25.548432
28432   5.307400   6.389007   6.158281   2.291025  ...    3.519932
28467  16.112886   6.125231  13.243070  12.171925  ...    7.124173
28534  16.237900  13.521272  17.046759  14.018700  ...   20.512704

                                                  P60                          \
                                                 Male
                                                  SAL
      M_P60_LPS 4 M_P60_LPS 5 M_P60_LPS 6 M_P60_Sal 1 M_P60_Sal 2 M_P60_Sal 3
1        8.666610   10.162162   10.506994   12.044844   15.205737   15.338470
4       12.326229    7.782548    9.160432   10.736356    4.997453   10.339587
9       39.532230   43.733161   36.450372   57.864156   36.084763   73.581530
10      16.890178   15.814274   17.120987   11.441391   11.678259    9.718479
11       5.369081    8.788723   18.877974   20.385011   20.706143   20.786472
...           ...         ...         ...         ...         ...         ...
28347   14.769420    9.991213   12.139496   27.566608   10.014777   32.674295
28407   10.410305   13.027308   13.355215   10.971551   13.772144    9.803588
28432    4.186542    3.304129    6.398227    5.049068    3.570666    4.811826
28467    7.943775   16.718497   21.709798   11.496457   10.840284   11.532913
28534    9.149037   13.478568   11.843857   12.505150    9.228056   16.824797

                                        gene
                       Female
                          SAL
      M_P60_Sal 4 F_P60_Sal 6
1       11.852764    2.358854           Scap
4        9.833710   14.677770          Taf9b
9       59.547866  140.014990       BC031181
10       9.317558    7.126444          Baz2b
11      27.257905   32.677220        Tmem204
...           ...         ...            ...
28347   27.544341   40.198997  4930592A05Rik
28407   11.753810    6.365685        Gm10336
28432    5.009955    1.869462  2810013P06Rik
28467   11.061719    7.567401  4931403E22Rik
28534    8.758784   21.788896  4930549G23Rik

[9431 rows x 61 columns]

In [25]:
rpkm.set_index('gene', inplace = True)

In [26]:
rpkm.to_csv('mdi_w_rpkm\\GSE99622_hanamsagar2017_rpkm_unmelted.csv')